version: 2

defaults: &defaults
  working_directory: ~/react-rxloop
  docker:
    - image: circleci/node:8-browsers

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-react-rxloop-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-react-rxloop-{{ .Branch }}
            - v1-react-rxloop
      - run:
          name: Installing Dependencies
          command: yarn
      - save_cache:
          paths:
            - ./node_modules
          key: v1-react-rxloop-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - react-rxloop

  lint-types:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Linting
          command: |
            yarn lint

  test-unit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Running Unit Tests
          command: |
            yarn test

  test-cover:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn coverage
      - run:
         name: report coverage stats for non-PRs
         command: |
           if [[ -z $CI_PULL_REQUEST ]]; then
             ./node_modules/.bin/codecov
           fi

workflows:
  version: 2
  install-and-parallel-test:
    jobs:
      - install
      - test-cover:
          requires:
            - install
      - lint-types:
          requires:
            - install
      - test-unit:
          requires:
            - install
